const newCards = [
{
  id: 1,
  property0: -2002,
  property1: "2002",
  property1E: "Since",
  property1D: "Seit",
  property2: 3,
  property2E: "Scarcity",
  property2D: "Knappheit",
  property3: 3,
  property3E: "Durability",
  property3D: "Lebensdauer",
  property4: 3,
  property4E: "Divisibility",
  property4D: "Teilbarkeit",
  property5: 3,
  property5E: "Transportability",
  property5D: "Transportierbarkeit",
  image: "/images/frontsite/euro.png",
  textE: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
  textD: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
},
{
  id: 2,
  property0: -2009,
  property1: "2009",
  property1E: "Since",
  property1D: "Seit",
  property2: 5,
  property2E: "Scarcity",
  property2D: "Knappheit",
  property3: 5,
  property3E: "Durability",
  property3D: "Lebensdauer",
  property4: 5,
  property4E: "Divisibility",
  property4D: "Teilbarkeit",
  property5: 5,
  property5E: "Transportability",
  property5D: "Transportierbarkeit",
  image: "/images/frontsite/bitcoin.png",
  textE: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
  textD: "d",
},
{
  id: 3,
  property0: -2014,
  property1: "2014",
  property1E: "Since",
  property1D: "Seit",
  property2: 4,
  property2E: "Scarcity",
  property2D: "Knappheit",
  property3: 4,
  property3E: "Durability",
  property3D: "Lebensdauer",
  property4: 4,
  property4E: "Divisibility",
  property4D: "Teilbarkeit",
  property5: 4,
  property5E: "Transportability",
  property5D: "Transportierbarkeit",
  image: "/images/frontsite/monero.png",
  textE: "4",
  textD: "4",
},
{
  id: 4,
  property0: -1484,
  property1: "1484",
  property1E: "Since",
  property1D: "Seit",
  property2: 1,
  property2E: "Scarcity",
  property2D: "Knappheit",
  property3: 1,
  property3E: "Durability",
  property3D: "Lebensdauer",
  property4: 1,
  property4E: "Divisibility",
  property4D: "Teilbarkeit",
  property5: 1,
  property5E: "Transportability",
  property5D: "Transportierbarkeit",
  image: "/images/frontsite/yen.png",
  textE: "1",
  textD: "1",
}
];
export default newCards;